import { Type } from '@google/genai';
import { ToolDefinition } from './types';

export const TOOL_REGISTRY: Record<string, ToolDefinition> = {
  // =========================================================================
  // 1. CUSTOMER INFORMATION TOOLS
  // =========================================================================
  search_menu: {
    id: 'tool_customer_search_menu',
    name: 'search_menu',
    toolName: 'search_menu',
    category: 'CUSTOMER_INFO',
    purpose: 'Search menu items by keyword, dish name, or category from Quetta Mahfil catalog.',
    description: 'Search menu items by keyword, dish name, or category from Quetta Mahfil catalog.',
    version: '1.0.0',
    status: 'IMPLEMENTED',
    parameters: {
      type: Type.OBJECT,
      properties: {
        query: { type: Type.STRING, description: "Search keyword, e.g. 'zafrani', 'nutella', 'paratha', 'kehwa'" },
        category: { type: Type.STRING, description: "Filter category: 'Tea & Kehwa', 'Chat Pata Paratha', 'Meetha Paratha', 'Milk Shakes', 'Fresh Juices', 'Fast Food'" }
      }
    },
    inputSchema: '{ query?: string, category?: string }',
    outputSchema: 'MenuListObject',
    requiresAuth: false,
    allowedRoles: ['anonymous', 'guest', 'customer', 'kitchen', 'staff', 'manager', 'admin', 'superadmin'],
    allowedActorTypes: ['guest', 'customer', 'kitchen', 'staff', 'manager', 'admin', 'superadmin'],
    requiredPermissions: ['menu.read'],
    requiresConfirmation: false,
    supportsIdempotency: false,
    riskLevel: 'READ_ONLY',
    rateLimit: 'standard',
    rateLimitClass: 'standard',
    auditRequired: false,
    enabled: true,
    timeoutMs: 5000,
    retryPolicy: { maxRetries: 2, retryable: true },
    destructive: false,
    sensitiveData: false,
    ownershipScope: 'public'
  },

  get_menu_item: {
    id: 'tool_customer_get_menu_item',
    name: 'get_menu_item',
    toolName: 'get_menu_item',
    category: 'CUSTOMER_INFO',
    purpose: 'Fetch detailed information for a single menu item by ID or name including stock status.',
    description: 'Get dish details including ingredients, allergen flags, and live kitchen stock status.',
    version: '1.0.0',
    status: 'IMPLEMENTED',
    parameters: {
      type: Type.OBJECT,
      properties: {
        itemIdOrName: { type: Type.STRING, description: 'Item identifier or exact name' }
      },
      required: ['itemIdOrName']
    },
    inputSchema: '{ itemIdOrName: string }',
    outputSchema: 'MenuItemObject',
    requiresAuth: false,
    allowedRoles: ['anonymous', 'guest', 'customer', 'kitchen', 'staff', 'manager', 'admin', 'superadmin'],
    allowedActorTypes: ['guest', 'customer', 'kitchen', 'staff', 'manager', 'admin', 'superadmin'],
    requiredPermissions: ['menu.read'],
    requiresConfirmation: false,
    supportsIdempotency: false,
    riskLevel: 'READ_ONLY',
    rateLimit: 'standard',
    rateLimitClass: 'standard',
    auditRequired: false,
    enabled: true,
    timeoutMs: 5000,
    retryPolicy: { maxRetries: 2, retryable: true },
    destructive: false,
    sensitiveData: false,
    ownershipScope: 'public'
  },

  get_menu_categories: {
    id: 'tool_customer_get_menu_categories',
    name: 'get_menu_categories',
    toolName: 'get_menu_categories',
    category: 'CUSTOMER_INFO',
    purpose: 'Retrieve all official culinary categories and available item counts in the Quetta Mahfil catalog.',
    description: 'List all menu categories with item counts and descriptions.',
    version: '1.0.0',
    status: 'IMPLEMENTED',
    parameters: { type: Type.OBJECT, properties: {} },
    inputSchema: '{}',
    outputSchema: 'CategoryListObject',
    requiresAuth: false,
    allowedRoles: ['anonymous', 'guest', 'customer', 'kitchen', 'staff', 'manager', 'admin', 'superadmin'],
    allowedActorTypes: ['guest', 'customer', 'kitchen', 'staff', 'manager', 'admin', 'superadmin'],
    requiredPermissions: ['menu.read'],
    requiresConfirmation: false,
    supportsIdempotency: false,
    riskLevel: 'READ_ONLY',
    rateLimit: 'standard',
    rateLimitClass: 'standard',
    auditRequired: false,
    enabled: true,
    timeoutMs: 5000,
    retryPolicy: { maxRetries: 2, retryable: true },
    destructive: false,
    sensitiveData: false,
    ownershipScope: 'public'
  },

  restaurant_information: {
    id: 'tool_customer_restaurant_information',
    name: 'restaurant_information',
    toolName: 'restaurant_information',
    category: 'CUSTOMER_INFO',
    purpose: 'Retrieve authoritative business details: 24/7 hours, exact Bahria Town address, parking, WiFi, cultural identity.',
    description: 'Get authoritative business details: location, 24/7 hours, WiFi, parking, cultural background.',
    version: '1.0.0',
    status: 'IMPLEMENTED',
    parameters: {
      type: Type.OBJECT,
      properties: {
        topic: { type: Type.STRING, description: "Topic: 'hours', 'location', 'wifi', 'founder', 'poetry', 'all'" }
      }
    },
    inputSchema: '{ topic?: string }',
    outputSchema: 'RestaurantInfoObject',
    requiresAuth: false,
    allowedRoles: ['anonymous', 'guest', 'customer', 'kitchen', 'staff', 'manager', 'admin', 'superadmin'],
    allowedActorTypes: ['guest', 'customer', 'kitchen', 'staff', 'manager', 'admin', 'superadmin'],
    requiredPermissions: ['restaurant.read'],
    requiresConfirmation: false,
    supportsIdempotency: false,
    riskLevel: 'READ_ONLY',
    rateLimit: 'standard',
    rateLimitClass: 'standard',
    auditRequired: false,
    enabled: true,
    timeoutMs: 5000,
    retryPolicy: { maxRetries: 2, retryable: true },
    destructive: false,
    sensitiveData: false,
    ownershipScope: 'public'
  },

  restaurant_hours: {
    id: 'tool_customer_restaurant_hours',
    name: 'restaurant_hours',
    toolName: 'restaurant_hours',
    category: 'CUSTOMER_INFO',
    purpose: 'Get detailed operating schedule, breakfast timings, and peak evening hours.',
    description: 'Authoritative operating hours for dining, takeaway, and delivery.',
    version: '1.0.0',
    status: 'IMPLEMENTED',
    parameters: { type: Type.OBJECT, properties: {} },
    inputSchema: '{}',
    outputSchema: 'OperatingHoursObject',
    requiresAuth: false,
    allowedRoles: ['anonymous', 'guest', 'customer', 'kitchen', 'staff', 'manager', 'admin', 'superadmin'],
    allowedActorTypes: ['guest', 'customer', 'kitchen', 'staff', 'manager', 'admin', 'superadmin'],
    requiredPermissions: ['restaurant.read'],
    requiresConfirmation: false,
    supportsIdempotency: false,
    riskLevel: 'READ_ONLY',
    rateLimit: 'standard',
    rateLimitClass: 'standard',
    auditRequired: false,
    enabled: true,
    timeoutMs: 5000,
    retryPolicy: { maxRetries: 2, retryable: true },
    destructive: false,
    sensitiveData: false,
    ownershipScope: 'public'
  },

  restaurant_contact: {
    id: 'tool_customer_restaurant_contact',
    name: 'restaurant_contact',
    toolName: 'restaurant_contact',
    category: 'CUSTOMER_INFO',
    purpose: 'Retrieve restaurant phone numbers, official WhatsApp order line, and exact physical location.',
    description: 'Get verified contact details and location for customer service and orders.',
    version: '1.0.0',
    status: 'IMPLEMENTED',
    parameters: { type: Type.OBJECT, properties: {} },
    inputSchema: '{}',
    outputSchema: 'ContactInfoObject',
    requiresAuth: false,
    allowedRoles: ['anonymous', 'guest', 'customer', 'kitchen', 'staff', 'manager', 'admin', 'superadmin'],
    allowedActorTypes: ['guest', 'customer', 'kitchen', 'staff', 'manager', 'admin', 'superadmin'],
    requiredPermissions: ['restaurant.read'],
    requiresConfirmation: false,
    supportsIdempotency: false,
    riskLevel: 'READ_ONLY',
    rateLimit: 'standard',
    rateLimitClass: 'standard',
    auditRequired: false,
    enabled: true,
    timeoutMs: 5000,
    retryPolicy: { maxRetries: 2, retryable: true },
    destructive: false,
    sensitiveData: false,
    ownershipScope: 'public'
  },

  customer_profile: {
    id: 'tool_customer_profile',
    name: 'customer_profile',
    toolName: 'customer_profile',
    category: 'CUSTOMER_ACCOUNT',
    purpose: 'Retrieve the authenticated patron profile, loyalty tier, and points balance.',
    description: 'Get authenticated user profile details, active orders count, and loyalty status.',
    version: '1.0.0',
    status: 'IMPLEMENTED',
    parameters: { type: Type.OBJECT, properties: {} },
    inputSchema: '{}',
    outputSchema: 'CustomerProfileObject',
    requiresAuth: true,
    allowedRoles: ['customer', 'staff', 'manager', 'admin', 'superadmin'],
    allowedActorTypes: ['customer', 'staff', 'manager', 'admin', 'superadmin'],
    requiredPermissions: ['profile.read'],
    requiresConfirmation: false,
    supportsIdempotency: false,
    riskLevel: 'READ_ONLY',
    rateLimit: 'standard',
    rateLimitClass: 'standard',
    auditRequired: false,
    enabled: true,
    timeoutMs: 5000,
    retryPolicy: { maxRetries: 2, retryable: true },
    destructive: false,
    sensitiveData: true,
    ownershipScope: 'user'
  },

  customer_memory: {
    id: 'tool_customer_memory',
    name: 'customer_memory',
    toolName: 'customer_memory',
    category: 'CUSTOMER_ACCOUNT',
    purpose: 'Retrieve the authenticated patron saved taste preferences, preferred chai sweetness, and dietary notes.',
    description: 'Access customer AI taste memory for personalized ordering recommendations.',
    version: '1.0.0',
    status: 'IMPLEMENTED',
    parameters: { type: Type.OBJECT, properties: {} },
    inputSchema: '{}',
    outputSchema: 'CustomerMemoryObject',
    requiresAuth: true,
    allowedRoles: ['customer', 'staff', 'manager', 'admin', 'superadmin'],
    allowedActorTypes: ['customer', 'staff', 'manager', 'admin', 'superadmin'],
    requiredPermissions: ['memory.read'],
    requiresConfirmation: false,
    supportsIdempotency: false,
    riskLevel: 'READ_ONLY',
    rateLimit: 'standard',
    rateLimitClass: 'standard',
    auditRequired: false,
    enabled: true,
    timeoutMs: 5000,
    retryPolicy: { maxRetries: 2, retryable: true },
    destructive: false,
    sensitiveData: true,
    ownershipScope: 'user'
  },

  // =========================================================================
  // 2. ORDER TOOLS
  // =========================================================================
  create_order: {
    id: 'tool_order_create_order',
    name: 'create_order',
    toolName: 'create_order',
    category: 'ORDER',
    purpose: 'Authoritatively create an order with verified server prices, stock verification, and duplicate-prevention idempotency.',
    description: 'Place an authoritative order with Quetta Mahfil Chai Khana.',
    version: '1.0.0',
    status: 'IMPLEMENTED',
    parameters: {
      type: Type.OBJECT,
      properties: {
        customerName: { type: Type.STRING, description: 'Customer full name' },
        phone: { type: Type.STRING, description: 'Contact phone number' },
        deliveryLocation: { type: Type.STRING, description: 'Delivery address or table number' },
        items: {
          type: Type.ARRAY,
          description: 'Ordered items and quantities',
          items: {
            type: Type.OBJECT,
            properties: {
              name: { type: Type.STRING, description: 'Item name from menu' },
              quantity: { type: Type.NUMBER, description: 'Quantity' }
            },
            required: ['name', 'quantity']
          }
        },
        paymentMethod: { type: Type.STRING, description: "'cash' for COD or 'sadapay_nayapay' for manual transfer" },
        idempotencyKey: { type: Type.STRING, description: 'Unique idempotency key' }
      },
      required: ['customerName', 'phone', 'deliveryLocation', 'items']
    },
    inputSchema: '{ customerName: string, phone: string, deliveryLocation: string, items: Array<{ name: string, quantity: number }>, paymentMethod?: string, idempotencyKey?: string }',
    outputSchema: 'OrderCreationResult',
    requiresAuth: false,
    allowedRoles: ['anonymous', 'guest', 'customer', 'kitchen', 'staff', 'manager', 'admin', 'superadmin'],
    allowedActorTypes: ['guest', 'customer', 'kitchen', 'staff', 'manager', 'admin', 'superadmin'],
    requiredPermissions: ['orders.create'],
    requiresConfirmation: false,
    supportsIdempotency: true,
    riskLevel: 'LOW_RISK_WRITE',
    rateLimit: 'strict',
    rateLimitClass: 'strict',
    auditRequired: true,
    enabled: true,
    timeoutMs: 8000,
    retryPolicy: { maxRetries: 0, retryable: false },
    destructive: false,
    sensitiveData: true,
    ownershipScope: 'order'
  },

  get_order: {
    id: 'tool_order_get_order',
    name: 'get_order',
    toolName: 'get_order',
    category: 'ORDER',
    purpose: 'Retrieve comprehensive order details, items breakdown, payment status, and fulfillment state.',
    description: 'Get full details of an existing order by ID.',
    version: '1.0.0',
    status: 'IMPLEMENTED',
    parameters: {
      type: Type.OBJECT,
      properties: {
        orderId: { type: Type.STRING, description: 'The Order ID, e.g. ORD-1042' }
      },
      required: ['orderId']
    },
    inputSchema: '{ orderId: string }',
    outputSchema: 'OrderDetailsObject',
    requiresAuth: false,
    allowedRoles: ['anonymous', 'guest', 'customer', 'kitchen', 'staff', 'manager', 'admin', 'superadmin'],
    allowedActorTypes: ['guest', 'customer', 'kitchen', 'staff', 'manager', 'admin', 'superadmin'],
    requiredPermissions: ['orders.read'],
    requiresConfirmation: false,
    supportsIdempotency: false,
    riskLevel: 'READ_ONLY',
    rateLimit: 'standard',
    rateLimitClass: 'standard',
    auditRequired: false,
    enabled: true,
    timeoutMs: 5000,
    retryPolicy: { maxRetries: 2, retryable: true },
    destructive: false,
    sensitiveData: false,
    ownershipScope: 'order'
  },

  update_order: {
    id: 'tool_order_update_order',
    name: 'update_order',
    toolName: 'update_order',
    category: 'ORDER',
    purpose: 'Update delivery instructions or contact notes for a pending order before preparation begins.',
    description: 'Update notes or delivery location for a pending order.',
    version: '1.0.0',
    status: 'IMPLEMENTED',
    parameters: {
      type: Type.OBJECT,
      properties: {
        orderId: { type: Type.STRING, description: 'The Order ID to update' },
        deliveryLocation: { type: Type.STRING, description: 'Updated delivery address' },
        notes: { type: Type.STRING, description: 'Special delivery notes' }
      },
      required: ['orderId']
    },
    inputSchema: '{ orderId: string, deliveryLocation?: string, notes?: string }',
    outputSchema: 'OrderUpdateResult',
    requiresAuth: true,
    allowedRoles: ['customer', 'staff', 'manager', 'admin', 'superadmin'],
    allowedActorTypes: ['customer', 'staff', 'manager', 'admin', 'superadmin'],
    requiredPermissions: ['orders.write'],
    requiresConfirmation: false,
    supportsIdempotency: true,
    riskLevel: 'LOW_RISK_WRITE',
    rateLimit: 'strict',
    rateLimitClass: 'strict',
    auditRequired: true,
    enabled: true,
    timeoutMs: 8000,
    retryPolicy: { maxRetries: 0, retryable: false },
    destructive: false,
    sensitiveData: true,
    ownershipScope: 'order'
  },

  cancel_order: {
    id: 'tool_order_cancel_order',
    name: 'cancel_order',
    toolName: 'cancel_order',
    category: 'ORDER',
    purpose: 'Cancel an order before it enters preparation. HIGH RISK: Requires explicit confirmation.',
    description: 'Cancel an active pending order. Requires explicit confirmation.',
    version: '1.0.0',
    status: 'IMPLEMENTED',
    parameters: {
      type: Type.OBJECT,
      properties: {
        orderId: { type: Type.STRING, description: 'The Order ID to cancel' },
        reason: { type: Type.STRING, description: 'Reason for cancellation' },
        confirmed: { type: Type.BOOLEAN, description: 'Must be true to execute cancellation' }
      },
      required: ['orderId']
    },
    inputSchema: '{ orderId: string, reason?: string, confirmed?: boolean }',
    outputSchema: 'CancellationResult',
    requiresAuth: true,
    allowedRoles: ['customer', 'staff', 'manager', 'admin', 'superadmin'],
    allowedActorTypes: ['customer', 'staff', 'manager', 'admin', 'superadmin'],
    requiredPermissions: ['orders.cancel'],
    requiresConfirmation: true,
    supportsIdempotency: true,
    riskLevel: 'HIGH_RISK_WRITE',
    rateLimit: 'strict',
    rateLimitClass: 'strict',
    auditRequired: true,
    enabled: true,
    timeoutMs: 8000,
    retryPolicy: { maxRetries: 0, retryable: false },
    destructive: true,
    sensitiveData: false,
    ownershipScope: 'order'
  },

  order_status: {
    id: 'tool_order_status',
    name: 'order_status',
    toolName: 'order_status',
    category: 'ORDER',
    purpose: 'Check live order status, preparation stage, and delivery ETA.',
    description: 'Check the real-time fulfillment status of an order.',
    version: '1.0.0',
    status: 'IMPLEMENTED',
    parameters: {
      type: Type.OBJECT,
      properties: {
        orderId: { type: Type.STRING, description: 'The Order ID, e.g. ORD-1042' }
      },
      required: ['orderId']
    },
    inputSchema: '{ orderId: string }',
    outputSchema: 'OrderStatusObject',
    requiresAuth: false,
    allowedRoles: ['anonymous', 'guest', 'customer', 'kitchen', 'staff', 'manager', 'admin', 'superadmin'],
    allowedActorTypes: ['guest', 'customer', 'kitchen', 'staff', 'manager', 'admin', 'superadmin'],
    requiredPermissions: ['orders.read'],
    requiresConfirmation: false,
    supportsIdempotency: false,
    riskLevel: 'READ_ONLY',
    rateLimit: 'standard',
    rateLimitClass: 'standard',
    auditRequired: false,
    enabled: true,
    timeoutMs: 5000,
    retryPolicy: { maxRetries: 2, retryable: true },
    destructive: false,
    sensitiveData: false,
    ownershipScope: 'order'
  },

  order_history: {
    id: 'tool_order_history',
    name: 'order_history',
    toolName: 'order_history',
    category: 'ORDER',
    purpose: 'Retrieve order history for the authenticated patron, or recent orders for staff/management.',
    description: 'List past orders placed by the authenticated patron.',
    version: '1.0.0',
    status: 'IMPLEMENTED',
    parameters: {
      type: Type.OBJECT,
      properties: {
        limit: { type: Type.NUMBER, description: 'Number of past orders to return (1-20)' }
      }
    },
    inputSchema: '{ limit?: number }',
    outputSchema: 'OrderHistoryList',
    requiresAuth: true,
    allowedRoles: ['customer', 'staff', 'manager', 'admin', 'superadmin'],
    allowedActorTypes: ['customer', 'staff', 'manager', 'admin', 'superadmin'],
    requiredPermissions: ['orders.read'],
    requiresConfirmation: false,
    supportsIdempotency: false,
    riskLevel: 'READ_ONLY',
    rateLimit: 'standard',
    rateLimitClass: 'standard',
    auditRequired: false,
    enabled: true,
    timeoutMs: 5000,
    retryPolicy: { maxRetries: 2, retryable: true },
    destructive: false,
    sensitiveData: true,
    ownershipScope: 'user'
  },

  // =========================================================================
  // 3. RESERVATION TOOLS
  // =========================================================================
  create_reservation: {
    id: 'tool_reservation_create_reservation',
    name: 'create_reservation',
    toolName: 'create_reservation',
    category: 'RESERVATION',
    purpose: 'Book a table or traditional private Hujra lounge with capacity checks and duplicate protection.',
    description: 'Book a table or private traditional Hujra lounge for guests.',
    version: '1.0.0',
    status: 'IMPLEMENTED',
    parameters: {
      type: Type.OBJECT,
      properties: {
        customerName: { type: Type.STRING, description: 'Name of the guest booking' },
        phone: { type: Type.STRING, description: 'Contact mobile phone number' },
        guests: { type: Type.NUMBER, description: 'Number of guests attending (1 to 50)' },
        date: { type: Type.STRING, description: 'Date (e.g. Tonight, Tomorrow, YYYY-MM-DD)' },
        time: { type: Type.STRING, description: 'Arrival time (e.g. 9:30 PM)' },
        notes: { type: Type.STRING, description: 'Special requests: Hujra floor seating, etc.' }
      },
      required: ['customerName', 'phone', 'guests', 'date', 'time']
    },
    inputSchema: '{ customerName: string, phone: string, guests: number, date: string, time: string, notes?: string }',
    outputSchema: 'ReservationResult',
    requiresAuth: false,
    allowedRoles: ['anonymous', 'guest', 'customer', 'kitchen', 'staff', 'manager', 'admin', 'superadmin'],
    allowedActorTypes: ['guest', 'customer', 'kitchen', 'staff', 'manager', 'admin', 'superadmin'],
    requiredPermissions: ['reservations.create'],
    requiresConfirmation: false,
    supportsIdempotency: true,
    riskLevel: 'LOW_RISK_WRITE',
    rateLimit: 'strict',
    rateLimitClass: 'strict',
    auditRequired: true,
    enabled: true,
    timeoutMs: 8000,
    retryPolicy: { maxRetries: 0, retryable: false },
    destructive: false,
    sensitiveData: true,
    ownershipScope: 'order'
  },

  get_reservation: {
    id: 'tool_reservation_get_reservation',
    name: 'get_reservation',
    toolName: 'get_reservation',
    category: 'RESERVATION',
    purpose: 'Look up reservation details, guest count, and seating area by reservation ID.',
    description: 'Get verified details of a table or Hujra reservation.',
    version: '1.0.0',
    status: 'IMPLEMENTED',
    parameters: {
      type: Type.OBJECT,
      properties: {
        reservationId: { type: Type.STRING, description: 'Reservation ID, e.g. RES-1042' }
      },
      required: ['reservationId']
    },
    inputSchema: '{ reservationId: string }',
    outputSchema: 'ReservationDetailsObject',
    requiresAuth: false,
    allowedRoles: ['anonymous', 'guest', 'customer', 'kitchen', 'staff', 'manager', 'admin', 'superadmin'],
    allowedActorTypes: ['guest', 'customer', 'kitchen', 'staff', 'manager', 'admin', 'superadmin'],
    requiredPermissions: ['reservations.read'],
    requiresConfirmation: false,
    supportsIdempotency: false,
    riskLevel: 'READ_ONLY',
    rateLimit: 'standard',
    rateLimitClass: 'standard',
    auditRequired: false,
    enabled: true,
    timeoutMs: 5000,
    retryPolicy: { maxRetries: 2, retryable: true },
    destructive: false,
    sensitiveData: false,
    ownershipScope: 'order'
  },

  update_reservation: {
    id: 'tool_reservation_update_reservation',
    name: 'update_reservation',
    toolName: 'update_reservation',
    category: 'RESERVATION',
    purpose: 'Update reservation party size, arrival time, or seating notes before confirmation.',
    description: 'Update guest count, time, or seating notes for an active reservation.',
    version: '1.0.0',
    status: 'IMPLEMENTED',
    parameters: {
      type: Type.OBJECT,
      properties: {
        reservationId: { type: Type.STRING, description: 'Reservation ID to update' },
        guests: { type: Type.NUMBER, description: 'Updated guest count' },
        time: { type: Type.STRING, description: 'Updated arrival time' },
        notes: { type: Type.STRING, description: 'Updated notes' }
      },
      required: ['reservationId']
    },
    inputSchema: '{ reservationId: string, guests?: number, time?: string, notes?: string }',
    outputSchema: 'ReservationUpdateResult',
    requiresAuth: false,
    allowedRoles: ['anonymous', 'guest', 'customer', 'staff', 'manager', 'admin', 'superadmin'],
    allowedActorTypes: ['guest', 'customer', 'staff', 'manager', 'admin', 'superadmin'],
    requiredPermissions: ['reservations.write'],
    requiresConfirmation: false,
    supportsIdempotency: true,
    riskLevel: 'LOW_RISK_WRITE',
    rateLimit: 'strict',
    rateLimitClass: 'strict',
    auditRequired: true,
    enabled: true,
    timeoutMs: 8000,
    retryPolicy: { maxRetries: 0, retryable: false },
    destructive: false,
    sensitiveData: true,
    ownershipScope: 'order'
  },

  cancel_reservation: {
    id: 'tool_reservation_cancel_reservation',
    name: 'cancel_reservation',
    toolName: 'cancel_reservation',
    category: 'RESERVATION',
    purpose: 'Cancel an existing table reservation. HIGH RISK: Requires explicit confirmation.',
    description: 'Cancel a booked table reservation. Requires explicit confirmation.',
    version: '1.0.0',
    status: 'IMPLEMENTED',
    parameters: {
      type: Type.OBJECT,
      properties: {
        reservationId: { type: Type.STRING, description: 'Reservation ID, e.g. RES-ABC123' },
        reason: { type: Type.STRING, description: 'Reason for cancellation' },
        confirmed: { type: Type.BOOLEAN, description: 'Must be true to execute cancellation' }
      },
      required: ['reservationId']
    },
    inputSchema: '{ reservationId: string, reason?: string, confirmed?: boolean }',
    outputSchema: 'CancellationResult',
    requiresAuth: false,
    allowedRoles: ['anonymous', 'guest', 'customer', 'staff', 'manager', 'admin', 'superadmin'],
    allowedActorTypes: ['guest', 'customer', 'staff', 'manager', 'admin', 'superadmin'],
    requiredPermissions: ['reservations.cancel'],
    requiresConfirmation: true,
    supportsIdempotency: true,
    riskLevel: 'HIGH_RISK_WRITE',
    rateLimit: 'strict',
    rateLimitClass: 'strict',
    auditRequired: true,
    enabled: true,
    timeoutMs: 8000,
    retryPolicy: { maxRetries: 0, retryable: false },
    destructive: true,
    sensitiveData: false,
    ownershipScope: 'order'
  },

  reservation_availability: {
    id: 'tool_reservation_availability',
    name: 'reservation_availability',
    toolName: 'reservation_availability',
    category: 'RESERVATION',
    purpose: 'Check live capacity and table/hujra availability for a date, time, and guest count.',
    description: 'Check available tables and traditional private Hujra suites.',
    version: '1.0.0',
    status: 'IMPLEMENTED',
    parameters: {
      type: Type.OBJECT,
      properties: {
        date: { type: Type.STRING, description: 'Target date (YYYY-MM-DD or Tonight/Tomorrow)' },
        time: { type: Type.STRING, description: 'Arrival time (e.g. 8:30 PM)' },
        guests: { type: Type.NUMBER, description: 'Party size (1-50)' }
      },
      required: ['date', 'time', 'guests']
    },
    inputSchema: '{ date: string, time: string, guests: number }',
    outputSchema: 'ReservationAvailabilityObject',
    requiresAuth: false,
    allowedRoles: ['anonymous', 'guest', 'customer', 'kitchen', 'staff', 'manager', 'admin', 'superadmin'],
    allowedActorTypes: ['guest', 'customer', 'kitchen', 'staff', 'manager', 'admin', 'superadmin'],
    requiredPermissions: ['reservations.read'],
    requiresConfirmation: false,
    supportsIdempotency: false,
    riskLevel: 'READ_ONLY',
    rateLimit: 'standard',
    rateLimitClass: 'standard',
    auditRequired: false,
    enabled: true,
    timeoutMs: 5000,
    retryPolicy: { maxRetries: 2, retryable: true },
    destructive: false,
    sensitiveData: false,
    ownershipScope: 'public'
  },

  // =========================================================================
  // 4. SUPPORT TOOLS
  // =========================================================================
  create_support_request: {
    id: 'tool_support_create_request',
    name: 'create_support_request',
    toolName: 'create_support_request',
    category: 'SUPPORT',
    purpose: 'Submit customer feedback, special requests, or waiter calls for immediate management attention.',
    description: 'Log customer feedback or inquiries for restaurant floor management.',
    version: '1.0.0',
    status: 'IMPLEMENTED',
    parameters: {
      type: Type.OBJECT,
      properties: {
        customerName: { type: Type.STRING, description: 'Customer name' },
        message: { type: Type.STRING, description: 'Feedback or inquiry message' },
        phone: { type: Type.STRING, description: 'Contact number if follow-up required' },
        priority: { type: Type.STRING, description: "'low' | 'normal' | 'high' | 'urgent'" }
      },
      required: ['customerName', 'message']
    },
    inputSchema: '{ customerName: string, message: string, phone?: string, priority?: string }',
    outputSchema: 'SupportTicketResult',
    requiresAuth: false,
    allowedRoles: ['anonymous', 'guest', 'customer', 'kitchen', 'staff', 'manager', 'admin', 'superadmin'],
    allowedActorTypes: ['guest', 'customer', 'kitchen', 'staff', 'manager', 'admin', 'superadmin'],
    requiredPermissions: ['support.write'],
    requiresConfirmation: false,
    supportsIdempotency: true,
    riskLevel: 'LOW_RISK_WRITE',
    rateLimit: 'standard',
    rateLimitClass: 'standard',
    auditRequired: true,
    enabled: true,
    timeoutMs: 5000,
    retryPolicy: { maxRetries: 1, retryable: true },
    destructive: false,
    sensitiveData: false,
    ownershipScope: 'public'
  },

  get_support_request: {
    id: 'tool_support_get_request',
    name: 'get_support_request',
    toolName: 'get_support_request',
    category: 'SUPPORT',
    purpose: 'Check status and management resolution for a previously submitted support ticket.',
    description: 'Retrieve status and notes for a support inquiry ticket.',
    version: '1.0.0',
    status: 'IMPLEMENTED',
    parameters: {
      type: Type.OBJECT,
      properties: {
        ticketId: { type: Type.STRING, description: 'Support ticket ID, e.g. TCK-1042' }
      },
      required: ['ticketId']
    },
    inputSchema: '{ ticketId: string }',
    outputSchema: 'SupportTicketStatusObject',
    requiresAuth: false,
    allowedRoles: ['anonymous', 'guest', 'customer', 'staff', 'manager', 'admin', 'superadmin'],
    allowedActorTypes: ['guest', 'customer', 'staff', 'manager', 'admin', 'superadmin'],
    requiredPermissions: ['support.read'],
    requiresConfirmation: false,
    supportsIdempotency: false,
    riskLevel: 'READ_ONLY',
    rateLimit: 'standard',
    rateLimitClass: 'standard',
    auditRequired: false,
    enabled: true,
    timeoutMs: 5000,
    retryPolicy: { maxRetries: 2, retryable: true },
    destructive: false,
    sensitiveData: false,
    ownershipScope: 'public'
  },

  customer_support_history: {
    id: 'tool_support_customer_history',
    name: 'customer_support_history',
    toolName: 'customer_support_history',
    category: 'SUPPORT',
    purpose: 'Retrieve all historical support tickets submitted by the authenticated customer.',
    description: 'List historical support tickets submitted by authenticated patron.',
    version: '1.0.0',
    status: 'IMPLEMENTED',
    parameters: { type: Type.OBJECT, properties: {} },
    inputSchema: '{}',
    outputSchema: 'SupportHistoryList',
    requiresAuth: true,
    allowedRoles: ['customer', 'staff', 'manager', 'admin', 'superadmin'],
    allowedActorTypes: ['customer', 'staff', 'manager', 'admin', 'superadmin'],
    requiredPermissions: ['support.read'],
    requiresConfirmation: false,
    supportsIdempotency: false,
    riskLevel: 'READ_ONLY',
    rateLimit: 'standard',
    rateLimitClass: 'standard',
    auditRequired: false,
    enabled: true,
    timeoutMs: 5000,
    retryPolicy: { maxRetries: 2, retryable: true },
    destructive: false,
    sensitiveData: true,
    ownershipScope: 'user'
  },

  // =========================================================================
  // 5. NOTIFICATION TOOLS
  // =========================================================================
  create_notification: {
    id: 'tool_notification_create',
    name: 'create_notification',
    toolName: 'create_notification',
    category: 'NOTIFICATION',
    purpose: 'Draft an operational, promotional, or system notification for staff or customers.',
    description: 'Create and draft a system or customer announcement.',
    version: '1.0.0',
    status: 'IMPLEMENTED',
    parameters: {
      type: Type.OBJECT,
      properties: {
        title: { type: Type.STRING, description: 'Notification title' },
        message: { type: Type.STRING, description: 'Notification body message' },
        audience: { type: Type.STRING, description: "'all' | 'customers' | 'staff' | 'kitchen'" },
        priority: { type: Type.STRING, description: "'low' | 'normal' | 'high'" }
      },
      required: ['title', 'message']
    },
    inputSchema: '{ title: string, message: string, audience?: string, priority?: string }',
    outputSchema: 'NotificationDraftResult',
    requiresAuth: true,
    allowedRoles: ['manager', 'admin', 'superadmin'],
    allowedActorTypes: ['manager', 'admin', 'superadmin'],
    requiredPermissions: ['notifications.send'],
    requiresConfirmation: false,
    supportsIdempotency: true,
    riskLevel: 'LOW_RISK_WRITE',
    rateLimit: 'privileged',
    rateLimitClass: 'privileged',
    auditRequired: true,
    enabled: true,
    timeoutMs: 8000,
    retryPolicy: { maxRetries: 1, retryable: true },
    destructive: false,
    sensitiveData: false,
    ownershipScope: 'system'
  },

  send_notification: {
    id: 'tool_notification_send',
    name: 'send_notification',
    toolName: 'send_notification',
    category: 'NOTIFICATION',
    purpose: 'Broadcast an immediate notification banner or operational message to restaurant app screens.',
    description: 'Broadcast active announcement to all user and staff interfaces.',
    version: '1.0.0',
    status: 'IMPLEMENTED',
    parameters: {
      type: Type.OBJECT,
      properties: {
        message: { type: Type.STRING, description: 'Broadcast message to transmit' }
      },
      required: ['message']
    },
    inputSchema: '{ message: string }',
    outputSchema: 'NotificationBroadcastResult',
    requiresAuth: true,
    allowedRoles: ['manager', 'admin', 'superadmin'],
    allowedActorTypes: ['manager', 'admin', 'superadmin'],
    requiredPermissions: ['notifications.send'],
    requiresConfirmation: false,
    supportsIdempotency: true,
    riskLevel: 'LOW_RISK_WRITE',
    rateLimit: 'privileged',
    rateLimitClass: 'privileged',
    auditRequired: true,
    enabled: true,
    timeoutMs: 8000,
    retryPolicy: { maxRetries: 1, retryable: true },
    destructive: false,
    sensitiveData: false,
    ownershipScope: 'system'
  },

  notification_status: {
    id: 'tool_notification_status',
    name: 'notification_status',
    toolName: 'notification_status',
    category: 'NOTIFICATION',
    purpose: 'View the currently active marquee announcement banner and notification delivery metrics.',
    description: 'Check active broadcast announcements and notification delivery status.',
    version: '1.0.0',
    status: 'IMPLEMENTED',
    parameters: { type: Type.OBJECT, properties: {} },
    inputSchema: '{}',
    outputSchema: 'NotificationStatusObject',
    requiresAuth: false,
    allowedRoles: ['anonymous', 'guest', 'customer', 'kitchen', 'staff', 'manager', 'admin', 'superadmin'],
    allowedActorTypes: ['guest', 'customer', 'kitchen', 'staff', 'manager', 'admin', 'superadmin'],
    requiredPermissions: ['restaurant.read'],
    requiresConfirmation: false,
    supportsIdempotency: false,
    riskLevel: 'READ_ONLY',
    rateLimit: 'standard',
    rateLimitClass: 'standard',
    auditRequired: false,
    enabled: true,
    timeoutMs: 5000,
    retryPolicy: { maxRetries: 2, retryable: true },
    destructive: false,
    sensitiveData: false,
    ownershipScope: 'public'
  },

  // =========================================================================
  // 6. LOYALTY TOOLS
  // =========================================================================
  loyalty_status: {
    id: 'tool_loyalty_status',
    name: 'loyalty_status',
    toolName: 'loyalty_status',
    category: 'LOYALTY',
    purpose: 'Check loyalty points balance, tier perks, and reward vouchers.',
    description: 'Get authoritative loyalty points balance and redemption vouchers.',
    version: '1.0.0',
    status: 'IMPLEMENTED',
    parameters: { type: Type.OBJECT, properties: {} },
    inputSchema: '{}',
    outputSchema: 'LoyaltyStatusObject',
    requiresAuth: true,
    allowedRoles: ['customer', 'staff', 'manager', 'admin', 'superadmin'],
    allowedActorTypes: ['customer', 'staff', 'manager', 'admin', 'superadmin'],
    requiredPermissions: ['loyalty.read'],
    requiresConfirmation: false,
    supportsIdempotency: false,
    riskLevel: 'READ_ONLY',
    rateLimit: 'standard',
    rateLimitClass: 'standard',
    auditRequired: false,
    enabled: true,
    timeoutMs: 5000,
    retryPolicy: { maxRetries: 2, retryable: true },
    destructive: false,
    sensitiveData: true,
    ownershipScope: 'user'
  },

  loyalty_history: {
    id: 'tool_loyalty_history',
    name: 'loyalty_history',
    toolName: 'loyalty_history',
    category: 'LOYALTY',
    purpose: 'Retrieve points earning transaction logs from past orders and visits.',
    description: 'List loyalty points transaction history from confirmed dining visits.',
    version: '1.0.0',
    status: 'IMPLEMENTED',
    parameters: { type: Type.OBJECT, properties: {} },
    inputSchema: '{}',
    outputSchema: 'LoyaltyHistoryList',
    requiresAuth: true,
    allowedRoles: ['customer', 'staff', 'manager', 'admin', 'superadmin'],
    allowedActorTypes: ['customer', 'staff', 'manager', 'admin', 'superadmin'],
    requiredPermissions: ['loyalty.read'],
    requiresConfirmation: false,
    supportsIdempotency: false,
    riskLevel: 'READ_ONLY',
    rateLimit: 'standard',
    rateLimitClass: 'standard',
    auditRequired: false,
    enabled: true,
    timeoutMs: 5000,
    retryPolicy: { maxRetries: 2, retryable: true },
    destructive: false,
    sensitiveData: true,
    ownershipScope: 'user'
  },

  eligible_rewards: {
    id: 'tool_loyalty_eligible_rewards',
    name: 'eligible_rewards',
    toolName: 'eligible_rewards',
    category: 'LOYALTY',
    purpose: 'List redeemable food and chai rewards based on current customer points balance.',
    description: 'Get list of free items and discounts the patron can claim with loyalty points.',
    version: '1.0.0',
    status: 'IMPLEMENTED',
    parameters: { type: Type.OBJECT, properties: {} },
    inputSchema: '{}',
    outputSchema: 'EligibleRewardsList',
    requiresAuth: true,
    allowedRoles: ['customer', 'staff', 'manager', 'admin', 'superadmin'],
    allowedActorTypes: ['customer', 'staff', 'manager', 'admin', 'superadmin'],
    requiredPermissions: ['loyalty.read'],
    requiresConfirmation: false,
    supportsIdempotency: false,
    riskLevel: 'READ_ONLY',
    rateLimit: 'standard',
    rateLimitClass: 'standard',
    auditRequired: false,
    enabled: true,
    timeoutMs: 5000,
    retryPolicy: { maxRetries: 2, retryable: true },
    destructive: false,
    sensitiveData: true,
    ownershipScope: 'user'
  },

  // =========================================================================
  // 7. RESTAURANT OPERATIONS TOOLS
  // =========================================================================
  kitchen_order_status: {
    id: 'tool_ops_kitchen_order_status',
    name: 'kitchen_order_status',
    toolName: 'kitchen_order_status',
    category: 'RESTAURANT_OPERATIONS',
    purpose: 'View active kitchen ticket queue, items currently preparing, and queue latency.',
    description: '[OPERATIONAL] View active KDS queue and kitchen prep load.',
    version: '1.0.0',
    status: 'IMPLEMENTED',
    parameters: { type: Type.OBJECT, properties: {} },
    inputSchema: '{}',
    outputSchema: 'KitchenQueueObject',
    requiresAuth: true,
    allowedRoles: ['kitchen', 'staff', 'manager', 'admin', 'superadmin'],
    allowedActorTypes: ['kitchen', 'staff', 'manager', 'admin', 'superadmin'],
    requiredPermissions: ['kitchen.read'],
    requiresConfirmation: false,
    supportsIdempotency: false,
    riskLevel: 'READ_ONLY',
    rateLimit: 'standard',
    rateLimitClass: 'standard',
    auditRequired: false,
    enabled: true,
    timeoutMs: 5000,
    retryPolicy: { maxRetries: 2, retryable: true },
    destructive: false,
    sensitiveData: false,
    ownershipScope: 'system'
  },

  kitchen_queue: {
    id: 'tool_ops_kitchen_queue',
    name: 'kitchen_queue',
    toolName: 'kitchen_queue',
    category: 'RESTAURANT_OPERATIONS',
    purpose: 'Detailed preparation queue metrics, average dish preparation latency, and queue bottleneck diagnostics.',
    description: '[OPERATIONAL] KDS queue metrics and live throughput diagnostics.',
    version: '1.0.0',
    status: 'IMPLEMENTED',
    parameters: { type: Type.OBJECT, properties: {} },
    inputSchema: '{}',
    outputSchema: 'KitchenQueueDiagnosticsObject',
    requiresAuth: true,
    allowedRoles: ['kitchen', 'staff', 'manager', 'admin', 'superadmin'],
    allowedActorTypes: ['kitchen', 'staff', 'manager', 'admin', 'superadmin'],
    requiredPermissions: ['kitchen.read'],
    requiresConfirmation: false,
    supportsIdempotency: false,
    riskLevel: 'READ_ONLY',
    rateLimit: 'standard',
    rateLimitClass: 'standard',
    auditRequired: false,
    enabled: true,
    timeoutMs: 5000,
    retryPolicy: { maxRetries: 2, retryable: true },
    destructive: false,
    sensitiveData: false,
    ownershipScope: 'system'
  },

  driver_dispatch: {
    id: 'tool_ops_driver_dispatch',
    name: 'driver_dispatch',
    toolName: 'driver_dispatch',
    category: 'RESTAURANT_OPERATIONS',
    purpose: 'View delivery dispatch queue, orders ready for rider pickup, and active Bahria Town rider assignments.',
    description: '[OPERATIONAL] View dispatch queue and delivery rider assignment board.',
    version: '1.0.0',
    status: 'IMPLEMENTED',
    parameters: {
      type: Type.OBJECT,
      properties: {
        filter: { type: Type.STRING, description: "'all' | 'ready' | 'in_transit'" }
      }
    },
    inputSchema: '{ filter?: string }',
    outputSchema: 'DriverDispatchBoardObject',
    requiresAuth: true,
    allowedRoles: ['staff', 'manager', 'admin', 'superadmin'],
    allowedActorTypes: ['staff', 'manager', 'admin', 'superadmin'],
    requiredPermissions: ['dispatch.read'],
    requiresConfirmation: false,
    supportsIdempotency: false,
    riskLevel: 'READ_ONLY',
    rateLimit: 'standard',
    rateLimitClass: 'standard',
    auditRequired: false,
    enabled: true,
    timeoutMs: 5000,
    retryPolicy: { maxRetries: 2, retryable: true },
    destructive: false,
    sensitiveData: false,
    ownershipScope: 'system'
  },

  delivery_status: {
    id: 'tool_ops_delivery_status',
    name: 'delivery_status',
    toolName: 'delivery_status',
    category: 'RESTAURANT_OPERATIONS',
    purpose: 'Check delivery stage and estimated arrival time for an active delivery order.',
    description: 'Check rider delivery stage and ETA for Bahria Town sectors.',
    version: '1.0.0',
    status: 'IMPLEMENTED',
    parameters: {
      type: Type.OBJECT,
      properties: {
        orderId: { type: Type.STRING, description: 'Order ID to track' }
      },
      required: ['orderId']
    },
    inputSchema: '{ orderId: string }',
    outputSchema: 'DeliveryStatusObject',
    requiresAuth: false,
    allowedRoles: ['anonymous', 'guest', 'customer', 'kitchen', 'staff', 'manager', 'admin', 'superadmin'],
    allowedActorTypes: ['guest', 'customer', 'kitchen', 'staff', 'manager', 'admin', 'superadmin'],
    requiredPermissions: ['orders.read'],
    requiresConfirmation: false,
    supportsIdempotency: false,
    riskLevel: 'READ_ONLY',
    rateLimit: 'standard',
    rateLimitClass: 'standard',
    auditRequired: false,
    enabled: true,
    timeoutMs: 5000,
    retryPolicy: { maxRetries: 2, retryable: true },
    destructive: false,
    sensitiveData: false,
    ownershipScope: 'order'
  },

  // =========================================================================
  // 8. ADMIN TOOLS
  // =========================================================================
  restaurant_configuration: {
    id: 'tool_admin_restaurant_config',
    name: 'restaurant_configuration',
    toolName: 'restaurant_configuration',
    category: 'ADMIN',
    purpose: 'View or update restaurant operational configuration (24/7 hours, delivery radius, banner announcement).',
    description: '[ADMIN] Inspect or modify restaurant operational configuration.',
    version: '1.0.0',
    status: 'IMPLEMENTED',
    parameters: {
      type: Type.OBJECT,
      properties: {
        action: { type: Type.STRING, description: "'read' | 'update'" },
        announcement: { type: Type.STRING, description: 'New global marquee message when updating' }
      }
    },
    inputSchema: '{ action?: string, announcement?: string }',
    outputSchema: 'RestaurantConfigObject',
    requiresAuth: true,
    allowedRoles: ['admin', 'superadmin'],
    allowedActorTypes: ['admin', 'superadmin'],
    requiredPermissions: ['configuration.read'],
    requiresConfirmation: false,
    supportsIdempotency: true,
    riskLevel: 'LOW_RISK_WRITE',
    rateLimit: 'privileged',
    rateLimitClass: 'privileged',
    auditRequired: true,
    enabled: true,
    timeoutMs: 8000,
    retryPolicy: { maxRetries: 1, retryable: true },
    destructive: false,
    sensitiveData: false,
    ownershipScope: 'system'
  },

  menu_management: {
    id: 'tool_admin_menu_management',
    name: 'menu_management',
    toolName: 'menu_management',
    category: 'ADMIN',
    purpose: '[ADMIN/KITCHEN] Manage menu items: update price, toggle in-stock availability (86).',
    description: '[ADMIN/KITCHEN] Manage menu pricing and item stock availability.',
    version: '1.0.0',
    status: 'IMPLEMENTED',
    parameters: {
      type: Type.OBJECT,
      properties: {
        action: { type: Type.STRING, description: "'update_price' | 'toggle_availability'" },
        itemIdOrName: { type: Type.STRING, description: 'Item name or ID' },
        price: { type: Type.NUMBER, description: 'New price in PKR (when updating price)' },
        isAvailable: { type: Type.BOOLEAN, description: 'true for available, false for 86 sold out' }
      },
      required: ['action', 'itemIdOrName']
    },
    inputSchema: '{ action: string, itemIdOrName: string, price?: number, isAvailable?: boolean }',
    outputSchema: 'MenuManagementResult',
    requiresAuth: true,
    allowedRoles: ['kitchen', 'staff', 'manager', 'admin', 'superadmin'],
    allowedActorTypes: ['kitchen', 'staff', 'manager', 'admin', 'superadmin'],
    requiredPermissions: ['menu.write'],
    requiresConfirmation: false,
    supportsIdempotency: true,
    riskLevel: 'LOW_RISK_WRITE',
    rateLimit: 'privileged',
    rateLimitClass: 'privileged',
    auditRequired: true,
    enabled: true,
    timeoutMs: 8000,
    retryPolicy: { maxRetries: 1, retryable: true },
    destructive: false,
    sensitiveData: false,
    ownershipScope: 'system'
  },

  order_management: {
    id: 'tool_admin_order_management',
    name: 'order_management',
    toolName: 'order_management',
    category: 'ADMIN',
    purpose: '[STAFF/ADMIN] Advance order lifecycle status across kitchen and delivery stages.',
    description: '[STAFF/ADMIN] Manage order status (confirmed, preparing, ready, out_for_delivery, completed).',
    version: '1.0.0',
    status: 'IMPLEMENTED',
    parameters: {
      type: Type.OBJECT,
      properties: {
        orderId: { type: Type.STRING, description: 'Order ID to advance' },
        status: { type: Type.STRING, description: "'confirmed' | 'preparing' | 'ready' | 'out_for_delivery' | 'completed' | 'cancelled'" },
        notes: { type: Type.STRING, description: 'Operational notes' }
      },
      required: ['orderId', 'status']
    },
    inputSchema: '{ orderId: string, status: string, notes?: string }',
    outputSchema: 'OrderManagementResult',
    requiresAuth: true,
    allowedRoles: ['kitchen', 'staff', 'manager', 'admin', 'superadmin'],
    allowedActorTypes: ['kitchen', 'staff', 'manager', 'admin', 'superadmin'],
    requiredPermissions: ['kitchen.write'],
    requiresConfirmation: false,
    supportsIdempotency: true,
    riskLevel: 'LOW_RISK_WRITE',
    rateLimit: 'privileged',
    rateLimitClass: 'privileged',
    auditRequired: true,
    enabled: true,
    timeoutMs: 8000,
    retryPolicy: { maxRetries: 1, retryable: true },
    destructive: false,
    sensitiveData: false,
    ownershipScope: 'order'
  },

  reservation_management: {
    id: 'tool_admin_reservation_management',
    name: 'reservation_management',
    toolName: 'reservation_management',
    category: 'ADMIN',
    purpose: '[STAFF/ADMIN] View and manage all guest reservations for today or specified date.',
    description: '[STAFF/ADMIN] List and manage reservations across dining hall and Hujra suites.',
    version: '1.0.0',
    status: 'IMPLEMENTED',
    parameters: {
      type: Type.OBJECT,
      properties: {
        filterDate: { type: Type.STRING, description: 'Date to filter, or empty for all' }
      }
    },
    inputSchema: '{ filterDate?: string }',
    outputSchema: 'ReservationListObject',
    requiresAuth: true,
    allowedRoles: ['staff', 'manager', 'admin', 'superadmin'],
    allowedActorTypes: ['staff', 'manager', 'admin', 'superadmin'],
    requiredPermissions: ['reservations.read'],
    requiresConfirmation: false,
    supportsIdempotency: false,
    riskLevel: 'READ_ONLY',
    rateLimit: 'privileged',
    rateLimitClass: 'privileged',
    auditRequired: false,
    enabled: true,
    timeoutMs: 8000,
    retryPolicy: { maxRetries: 2, retryable: true },
    destructive: false,
    sensitiveData: true,
    ownershipScope: 'system'
  },

  customer_management: {
    id: 'tool_admin_customer_management',
    name: 'customer_management',
    toolName: 'customer_management',
    category: 'ADMIN',
    purpose: '[ADMIN/MANAGER] View registered customer directory, patron loyalty standing, and order volume metrics.',
    description: '[ADMIN/MANAGER] Customer directory, loyalty tier standing, and patron metrics.',
    version: '1.0.0',
    status: 'IMPLEMENTED',
    parameters: {
      type: Type.OBJECT,
      properties: {
        query: { type: Type.STRING, description: 'Search name, phone, or UID' }
      }
    },
    inputSchema: '{ query?: string }',
    outputSchema: 'CustomerDirectoryObject',
    requiresAuth: true,
    allowedRoles: ['manager', 'admin', 'superadmin'],
    allowedActorTypes: ['manager', 'admin', 'superadmin'],
    requiredPermissions: ['customers.read'],
    requiresConfirmation: false,
    supportsIdempotency: false,
    riskLevel: 'READ_ONLY',
    rateLimit: 'privileged',
    rateLimitClass: 'privileged',
    auditRequired: false,
    enabled: true,
    timeoutMs: 8000,
    retryPolicy: { maxRetries: 2, retryable: true },
    destructive: false,
    sensitiveData: true,
    ownershipScope: 'system'
  },

  notification_management: {
    id: 'tool_admin_notification_management',
    name: 'notification_management',
    toolName: 'notification_management',
    category: 'ADMIN',
    purpose: '[ADMIN] Manage global marquee announcements and promotional messages.',
    description: '[ADMIN] Manage global marquee announcements and promotional messages.',
    version: '1.0.0',
    status: 'IMPLEMENTED',
    parameters: {
      type: Type.OBJECT,
      properties: {
        message: { type: Type.STRING, description: 'New marquee announcement text' }
      },
      required: ['message']
    },
    inputSchema: '{ message: string }',
    outputSchema: 'AnnouncementResult',
    requiresAuth: true,
    allowedRoles: ['admin', 'superadmin'],
    allowedActorTypes: ['admin', 'superadmin'],
    requiredPermissions: ['configuration.write'],
    requiresConfirmation: false,
    supportsIdempotency: true,
    riskLevel: 'LOW_RISK_WRITE',
    rateLimit: 'privileged',
    rateLimitClass: 'privileged',
    auditRequired: true,
    enabled: true,
    timeoutMs: 8000,
    retryPolicy: { maxRetries: 1, retryable: true },
    destructive: false,
    sensitiveData: false,
    ownershipScope: 'system'
  },

  operational_reports: {
    id: 'tool_admin_operational_reports',
    name: 'operational_reports',
    toolName: 'operational_reports',
    category: 'ADMIN',
    purpose: '[ADMIN/MANAGER] Comprehensive operational overview of orders, revenue, active tickets, and table occupancy.',
    description: '[ADMIN/MANAGER] Comprehensive operational report on sales, active reservations, popular items.',
    version: '1.0.0',
    status: 'IMPLEMENTED',
    parameters: {
      type: Type.OBJECT,
      properties: {
        timeframe: { type: Type.STRING, description: "Timeframe: 'today', 'shift', 'week'" }
      }
    },
    inputSchema: '{ timeframe?: string }',
    outputSchema: 'OperationalReportObject',
    requiresAuth: true,
    allowedRoles: ['manager', 'admin', 'superadmin'],
    allowedActorTypes: ['manager', 'admin', 'superadmin'],
    requiredPermissions: ['reports.read'],
    requiresConfirmation: false,
    supportsIdempotency: false,
    riskLevel: 'READ_ONLY',
    rateLimit: 'privileged',
    rateLimitClass: 'privileged',
    auditRequired: false,
    enabled: true,
    timeoutMs: 8000,
    retryPolicy: { maxRetries: 2, retryable: true },
    destructive: false,
    sensitiveData: true,
    ownershipScope: 'system'
  },

  // =========================================================================
  // 9. AI & CONTEXT TOOLS
  // =========================================================================
  restaurant_knowledge_search: {
    id: 'tool_ai_knowledge_search',
    name: 'restaurant_knowledge_search',
    toolName: 'restaurant_knowledge_search',
    category: 'AI',
    purpose: 'Search Quetta Mahfil 32-year heritage lore, Pashtun/Balochi culture, traditional poetry, and brewing traditions.',
    description: 'Retrieve verified cultural lore, brewing heritage, and poetry.',
    version: '1.0.0',
    status: 'IMPLEMENTED',
    parameters: {
      type: Type.OBJECT,
      properties: {
        query: { type: Type.STRING, description: "Topic to search: 'tea_brewing', 'founder', 'hujra_culture', 'poetry', 'paratha_history'" }
      },
      required: ['query']
    },
    inputSchema: '{ query: string }',
    outputSchema: 'KnowledgeSearchResultObject',
    requiresAuth: false,
    allowedRoles: ['anonymous', 'guest', 'customer', 'kitchen', 'staff', 'manager', 'admin', 'superadmin'],
    allowedActorTypes: ['guest', 'customer', 'kitchen', 'staff', 'manager', 'admin', 'superadmin'],
    requiredPermissions: ['restaurant.read'],
    requiresConfirmation: false,
    supportsIdempotency: false,
    riskLevel: 'READ_ONLY',
    rateLimit: 'standard',
    rateLimitClass: 'standard',
    auditRequired: false,
    enabled: true,
    timeoutMs: 5000,
    retryPolicy: { maxRetries: 2, retryable: true },
    destructive: false,
    sensitiveData: false,
    ownershipScope: 'public'
  },

  customer_context: {
    id: 'tool_ai_customer_context',
    name: 'customer_context',
    toolName: 'customer_context',
    category: 'AI',
    purpose: 'Synthesize verified customer profile, taste memory, and recent orders for personalized AI assistance.',
    description: 'Synthesize full context (profile, memory, recent orders) for caller.',
    version: '1.0.0',
    status: 'IMPLEMENTED',
    parameters: { type: Type.OBJECT, properties: {} },
    inputSchema: '{}',
    outputSchema: 'CustomerContextObject',
    requiresAuth: true,
    allowedRoles: ['customer', 'staff', 'manager', 'admin', 'superadmin'],
    allowedActorTypes: ['customer', 'staff', 'manager', 'admin', 'superadmin'],
    requiredPermissions: ['memory.read'],
    requiresConfirmation: false,
    supportsIdempotency: false,
    riskLevel: 'READ_ONLY',
    rateLimit: 'standard',
    rateLimitClass: 'standard',
    auditRequired: false,
    enabled: true,
    timeoutMs: 5000,
    retryPolicy: { maxRetries: 2, retryable: true },
    destructive: false,
    sensitiveData: true,
    ownershipScope: 'user'
  },

  conversation_context: {
    id: 'tool_ai_conversation_context',
    name: 'conversation_context',
    toolName: 'conversation_context',
    category: 'AI',
    purpose: 'Retrieve active conversational state, order drafting context, and pending confirmation gates.',
    description: 'Retrieve session context and active tool confirmation states.',
    version: '1.0.0',
    status: 'IMPLEMENTED',
    parameters: { type: Type.OBJECT, properties: {} },
    inputSchema: '{}',
    outputSchema: 'ConversationContextObject',
    requiresAuth: false,
    allowedRoles: ['anonymous', 'guest', 'customer', 'kitchen', 'staff', 'manager', 'admin', 'superadmin'],
    allowedActorTypes: ['guest', 'customer', 'kitchen', 'staff', 'manager', 'admin', 'superadmin'],
    requiredPermissions: ['restaurant.read'],
    requiresConfirmation: false,
    supportsIdempotency: false,
    riskLevel: 'READ_ONLY',
    rateLimit: 'standard',
    rateLimitClass: 'standard',
    auditRequired: false,
    enabled: true,
    timeoutMs: 5000,
    retryPolicy: { maxRetries: 2, retryable: true },
    destructive: false,
    sensitiveData: false,
    ownershipScope: 'public'
  },

  // =========================================================================
  // 10. EXPLICIT NOT_IMPLEMENTED / REQUIRES_EXTERNAL_SERVICE TOOLS
  // =========================================================================
  automated_bank_refund: {
    id: 'tool_fin_automated_bank_refund',
    name: 'automated_bank_refund',
    toolName: 'automated_bank_refund',
    category: 'ORDER',
    purpose: 'Automated direct bank reversal for paid orders. REQUIRES PAKISTANI BANKING INTEGRATION.',
    description: 'Automated bank reversal. Currently REQUIRES EXTERNAL SERVICE (SadaPay/JazzCash Gateway).',
    version: '1.0.0',
    status: 'NOT_IMPLEMENTED',
    statusReason: 'Requires Pakistani banking merchant API integration (SadaPay/JazzCash/1Link Gateway). Use manual refund workflow.',
    parameters: {
      type: Type.OBJECT,
      properties: {
        orderId: { type: Type.STRING, description: 'Order ID for refund' },
        amount: { type: Type.NUMBER, description: 'Amount in PKR' }
      },
      required: ['orderId', 'amount']
    },
    inputSchema: '{ orderId: string, amount: number }',
    outputSchema: 'BankRefundResult',
    requiresAuth: true,
    allowedRoles: ['admin', 'superadmin'],
    allowedActorTypes: ['admin', 'superadmin'],
    requiredPermissions: ['orders.cancel'],
    requiresConfirmation: true,
    supportsIdempotency: true,
    riskLevel: 'CRITICAL_ADMIN',
    rateLimit: 'privileged',
    rateLimitClass: 'privileged',
    auditRequired: true,
    enabled: false,
    timeoutMs: 10000,
    retryPolicy: { maxRetries: 0, retryable: false },
    destructive: true,
    sensitiveData: true,
    ownershipScope: 'order'
  },

  driver_live_gps_stream: {
    id: 'tool_ops_driver_live_gps_stream',
    name: 'driver_live_gps_stream',
    toolName: 'driver_live_gps_stream',
    category: 'DISPATCH',
    purpose: 'Real-time GPS coordinate telemetry stream for delivery bikes. REQUIRES HARDWARE TELEMETRY.',
    description: 'Live GPS coordinate telemetry stream for delivery bikes. REQUIRES HARDWARE INTEGRATION.',
    version: '1.0.0',
    status: 'NOT_IMPLEMENTED',
    statusReason: 'Requires vehicle GPS hardware integration or rider mobile GPS SDK.',
    parameters: {
      type: Type.OBJECT,
      properties: {
        riderId: { type: Type.STRING, description: 'Rider ID' }
      },
      required: ['riderId']
    },
    inputSchema: '{ riderId: string }',
    outputSchema: 'GpsTelemetryStream',
    requiresAuth: true,
    allowedRoles: ['staff', 'manager', 'admin', 'superadmin'],
    allowedActorTypes: ['staff', 'manager', 'admin', 'superadmin'],
    requiredPermissions: ['dispatch.read'],
    requiresConfirmation: false,
    supportsIdempotency: false,
    riskLevel: 'READ_ONLY',
    rateLimit: 'privileged',
    rateLimitClass: 'privileged',
    auditRequired: false,
    enabled: false,
    timeoutMs: 5000,
    retryPolicy: { maxRetries: 0, retryable: false },
    destructive: false,
    sensitiveData: true,
    ownershipScope: 'system'
  },

  automated_loyalty_point_purchase: {
    id: 'tool_loyalty_point_purchase',
    name: 'automated_loyalty_point_purchase',
    toolName: 'automated_loyalty_point_purchase',
    category: 'LOYALTY',
    purpose: 'Direct purchasing of loyalty points with card. RESTRICTED BY BUSINESS RULES.',
    description: 'Direct point purchasing. RESTRICTED BY BUSINESS RULES.',
    version: '1.0.0',
    status: 'NOT_IMPLEMENTED',
    statusReason: 'Points can only be earned through verified restaurant orders. Direct point purchasing is disabled.',
    parameters: {
      type: Type.OBJECT,
      properties: {
        pointsToBuy: { type: Type.NUMBER, description: 'Points amount' }
      },
      required: ['pointsToBuy']
    },
    inputSchema: '{ pointsToBuy: number }',
    outputSchema: 'PointPurchaseResult',
    requiresAuth: true,
    allowedRoles: ['customer', 'admin', 'superadmin'],
    allowedActorTypes: ['customer', 'admin', 'superadmin'],
    requiredPermissions: ['loyalty.read'],
    requiresConfirmation: false,
    supportsIdempotency: false,
    riskLevel: 'LOW_RISK_WRITE',
    rateLimit: 'strict',
    rateLimitClass: 'strict',
    auditRequired: false,
    enabled: false,
    timeoutMs: 5000,
    retryPolicy: { maxRetries: 0, retryable: false },
    destructive: false,
    sensitiveData: false,
    ownershipScope: 'user'
  },

  // =========================================================================
  // 11. SUPER ADMIN TOOLS
  // =========================================================================
  superadmin_system_diagnostics: {
    id: 'tool_superadmin_system_diagnostics',
    name: 'superadmin_system_diagnostics',
    toolName: 'superadmin_system_diagnostics',
    category: 'SUPER_ADMIN',
    purpose: '[SUPER ADMIN ONLY] View deep security diagnostics, audit log count, and cloud configuration status.',
    description: '[SUPER ADMIN ONLY] View security health, audit trails, and infrastructure integrity.',
    version: '1.0.0',
    status: 'IMPLEMENTED',
    parameters: { type: Type.OBJECT, properties: {} },
    inputSchema: '{}',
    outputSchema: 'SystemDiagnosticsObject',
    requiresAuth: true,
    allowedRoles: ['superadmin'],
    allowedActorTypes: ['superadmin'],
    requiredPermissions: ['*'],
    requiresConfirmation: false,
    supportsIdempotency: false,
    riskLevel: 'CRITICAL_ADMIN',
    rateLimit: 'privileged',
    rateLimitClass: 'privileged',
    auditRequired: true,
    enabled: true,
    timeoutMs: 8000,
    retryPolicy: { maxRetries: 1, retryable: true },
    destructive: false,
    sensitiveData: true,
    ownershipScope: 'system'
  },

  // =========================================================================
  // 12. LEGACY & CANONICAL COMPATIBILITY TOOLS
  // =========================================================================
  get_restaurant_info: {
    id: 'tool_customer_restaurant_info_legacy',
    name: 'get_restaurant_info',
    toolName: 'get_restaurant_info',
    category: 'CUSTOMER_INFO',
    purpose: 'Retrieve authoritative business details: 24/7 hours, exact Bahria Town address, parking, WiFi, cultural identity.',
    description: 'Get authoritative business details: location, 24/7 hours, WiFi, parking, cultural background.',
    version: '1.0.0',
    status: 'IMPLEMENTED',
    parameters: {
      type: Type.OBJECT,
      properties: {
        topic: { type: Type.STRING, description: "Topic: 'hours', 'location', 'wifi', 'founder', 'poetry', 'all'" }
      }
    },
    inputSchema: '{ topic?: string }',
    outputSchema: 'RestaurantInfoObject',
    requiresAuth: false,
    allowedRoles: ['anonymous', 'guest', 'customer', 'kitchen', 'staff', 'manager', 'admin', 'superadmin'],
    allowedActorTypes: ['guest', 'customer', 'kitchen', 'staff', 'manager', 'admin', 'superadmin'],
    requiredPermissions: ['restaurant.read'],
    requiresConfirmation: false,
    supportsIdempotency: false,
    riskLevel: 'READ_ONLY',
    rateLimit: 'standard',
    rateLimitClass: 'standard',
    auditRequired: false,
    enabled: true,
    timeoutMs: 5000,
    retryPolicy: { maxRetries: 2, retryable: true },
    destructive: false,
    sensitiveData: false,
    ownershipScope: 'public'
  },

  get_restaurant_hours: {
    id: 'tool_customer_restaurant_hours_legacy',
    name: 'get_restaurant_hours',
    toolName: 'get_restaurant_hours',
    category: 'CUSTOMER_INFO',
    purpose: 'Get detailed operating schedule, breakfast timings, and peak evening hours.',
    description: 'Authoritative operating hours for dining, takeaway, and delivery.',
    version: '1.0.0',
    status: 'IMPLEMENTED',
    parameters: { type: Type.OBJECT, properties: {} },
    inputSchema: '{}',
    outputSchema: 'OperatingHoursObject',
    requiresAuth: false,
    allowedRoles: ['anonymous', 'guest', 'customer', 'kitchen', 'staff', 'manager', 'admin', 'superadmin'],
    allowedActorTypes: ['guest', 'customer', 'kitchen', 'staff', 'manager', 'admin', 'superadmin'],
    requiredPermissions: ['restaurant.read'],
    requiresConfirmation: false,
    supportsIdempotency: false,
    riskLevel: 'READ_ONLY',
    rateLimit: 'standard',
    rateLimitClass: 'standard',
    auditRequired: false,
    enabled: true,
    timeoutMs: 5000,
    retryPolicy: { maxRetries: 2, retryable: true },
    destructive: false,
    sensitiveData: false,
    ownershipScope: 'public'
  },

  get_menu: {
    id: 'tool_customer_get_menu_legacy',
    name: 'get_menu',
    toolName: 'get_menu',
    category: 'CUSTOMER_INFO',
    purpose: 'Retrieve real-time authoritative menu items, prices, and stock availability from catalog.',
    description: 'Get real-time authoritative menu items, prices, and stock availability from Quetta Mahfil catalog.',
    version: '1.0.0',
    status: 'IMPLEMENTED',
    parameters: {
      type: Type.OBJECT,
      properties: {
        category: { type: Type.STRING, description: "Filter: 'Tea & Kehwa', 'Chat Pata Paratha', 'Meetha Paratha', 'Milk Shakes', 'Fresh Juices', 'Fast Food'" },
        query: { type: Type.STRING, description: "Search keyword, e.g. 'zafrani', 'nutella', 'paratha'" }
      }
    },
    inputSchema: '{ category?: string, query?: string }',
    outputSchema: 'MenuListObject',
    requiresAuth: false,
    allowedRoles: ['anonymous', 'guest', 'customer', 'kitchen', 'staff', 'manager', 'admin', 'superadmin'],
    allowedActorTypes: ['guest', 'customer', 'kitchen', 'staff', 'manager', 'admin', 'superadmin'],
    requiredPermissions: ['menu.read'],
    requiresConfirmation: false,
    supportsIdempotency: false,
    riskLevel: 'READ_ONLY',
    rateLimit: 'standard',
    rateLimitClass: 'standard',
    auditRequired: false,
    enabled: true,
    timeoutMs: 5000,
    retryPolicy: { maxRetries: 2, retryable: true },
    destructive: false,
    sensitiveData: false,
    ownershipScope: 'public'
  },

  calculate_order_quote: {
    id: 'tool_order_calculate_quote_legacy',
    name: 'calculate_order_quote',
    toolName: 'calculate_order_quote',
    category: 'ORDER',
    purpose: 'Calculate authoritative server pricing quote including subtotal, delivery fee, and total in PKR.',
    description: 'Calculate authoritative server pricing quote for food/drinks items in PKR.',
    version: '1.0.0',
    status: 'IMPLEMENTED',
    parameters: {
      type: Type.OBJECT,
      properties: {
        items: {
          type: Type.ARRAY,
          description: 'List of items requested with quantities',
          items: {
            type: Type.OBJECT,
            properties: {
              name: { type: Type.STRING, description: 'Name of the dish or drink' },
              quantity: { type: Type.NUMBER, description: 'Quantity ordered' }
            },
            required: ['name', 'quantity']
          }
        },
        deliveryLocation: { type: Type.STRING, description: 'Delivery destination in Bahria Town or Lahore' }
      },
      required: ['items']
    },
    inputSchema: '{ items: Array<{ name: string, quantity: number }>, deliveryLocation?: string }',
    outputSchema: 'OrderQuoteObject',
    requiresAuth: false,
    allowedRoles: ['anonymous', 'guest', 'customer', 'kitchen', 'staff', 'manager', 'admin', 'superadmin'],
    allowedActorTypes: ['guest', 'customer', 'kitchen', 'staff', 'manager', 'admin', 'superadmin'],
    requiredPermissions: ['orders.read'],
    requiresConfirmation: false,
    supportsIdempotency: false,
    riskLevel: 'READ_ONLY',
    rateLimit: 'standard',
    rateLimitClass: 'standard',
    auditRequired: false,
    enabled: true,
    timeoutMs: 5000,
    retryPolicy: { maxRetries: 2, retryable: true },
    destructive: false,
    sensitiveData: false,
    ownershipScope: 'public'
  },

  get_customer_profile: {
    id: 'tool_customer_profile_legacy',
    name: 'get_customer_profile',
    toolName: 'get_customer_profile',
    category: 'CUSTOMER_ACCOUNT',
    purpose: 'Retrieve the authenticated patron profile, loyalty tier, and points balance.',
    description: 'Get authenticated user profile details, active orders count, and loyalty status.',
    version: '1.0.0',
    status: 'IMPLEMENTED',
    parameters: { type: Type.OBJECT, properties: {} },
    inputSchema: '{}',
    outputSchema: 'CustomerProfileObject',
    requiresAuth: true,
    allowedRoles: ['customer', 'staff', 'manager', 'admin', 'superadmin'],
    allowedActorTypes: ['customer', 'staff', 'manager', 'admin', 'superadmin'],
    requiredPermissions: ['profile.read'],
    requiresConfirmation: false,
    supportsIdempotency: false,
    riskLevel: 'READ_ONLY',
    rateLimit: 'standard',
    rateLimitClass: 'standard',
    auditRequired: false,
    enabled: true,
    timeoutMs: 5000,
    retryPolicy: { maxRetries: 2, retryable: true },
    destructive: false,
    sensitiveData: true,
    ownershipScope: 'user'
  },

  get_customer_memory: {
    id: 'tool_customer_memory_legacy',
    name: 'get_customer_memory',
    toolName: 'get_customer_memory',
    category: 'CUSTOMER_ACCOUNT',
    purpose: 'Retrieve the authenticated patron saved taste preferences, preferred chai sweetness, and dietary notes.',
    description: 'Access customer AI taste memory for personalized ordering recommendations.',
    version: '1.0.0',
    status: 'IMPLEMENTED',
    parameters: { type: Type.OBJECT, properties: {} },
    inputSchema: '{}',
    outputSchema: 'CustomerMemoryObject',
    requiresAuth: true,
    allowedRoles: ['customer', 'staff', 'manager', 'admin', 'superadmin'],
    allowedActorTypes: ['customer', 'staff', 'manager', 'admin', 'superadmin'],
    requiredPermissions: ['memory.read'],
    requiresConfirmation: false,
    supportsIdempotency: false,
    riskLevel: 'READ_ONLY',
    rateLimit: 'standard',
    rateLimitClass: 'standard',
    auditRequired: false,
    enabled: true,
    timeoutMs: 5000,
    retryPolicy: { maxRetries: 2, retryable: true },
    destructive: false,
    sensitiveData: true,
    ownershipScope: 'user'
  },

  update_customer_preferences: {
    id: 'tool_customer_update_preferences_legacy',
    name: 'update_customer_preferences',
    toolName: 'update_customer_preferences',
    category: 'CUSTOMER_ACCOUNT',
    purpose: 'Update customer taste preferences and dietary restrictions in privacy-safe AI memory.',
    description: 'Save customer taste preferences (chai sweetness, spice level, favorite dishes) to private memory.',
    version: '1.0.0',
    status: 'IMPLEMENTED',
    parameters: {
      type: Type.OBJECT,
      properties: {
        preferences: { type: Type.ARRAY, items: { type: Type.STRING }, description: 'List of taste preferences' },
        teaPreferences: { type: Type.STRING, description: 'Specific tea preference (e.g. Karak, half sugar)' },
        dietaryNotes: { type: Type.ARRAY, items: { type: Type.STRING }, description: 'Allergies or dietary restrictions' },
        preferredLanguage: { type: Type.STRING, description: 'Urdu, English, or Roman Urdu' }
      }
    },
    inputSchema: '{ preferences?: string[], teaPreferences?: string, dietaryNotes?: string[], preferredLanguage?: string }',
    outputSchema: 'CustomerMemoryObject',
    requiresAuth: true,
    allowedRoles: ['customer', 'staff', 'manager', 'admin', 'superadmin'],
    allowedActorTypes: ['customer', 'staff', 'manager', 'admin', 'superadmin'],
    requiredPermissions: ['memory.write'],
    requiresConfirmation: false,
    supportsIdempotency: true,
    riskLevel: 'LOW_RISK_WRITE',
    rateLimit: 'standard',
    rateLimitClass: 'standard',
    auditRequired: false,
    enabled: true,
    timeoutMs: 5000,
    retryPolicy: { maxRetries: 2, retryable: true },
    destructive: false,
    sensitiveData: true,
    ownershipScope: 'user'
  },

  get_order_status: {
    id: 'tool_order_get_status_legacy',
    name: 'get_order_status',
    toolName: 'get_order_status',
    category: 'ORDER',
    purpose: 'Check live order status, preparation stage, and delivery ETA.',
    description: 'Check the real-time fulfillment status of an order.',
    version: '1.0.0',
    status: 'IMPLEMENTED',
    parameters: {
      type: Type.OBJECT,
      properties: {
        orderId: { type: Type.STRING, description: 'The Order ID, e.g. ORD-1042' }
      },
      required: ['orderId']
    },
    inputSchema: '{ orderId: string }',
    outputSchema: 'OrderStatusObject',
    requiresAuth: false,
    allowedRoles: ['anonymous', 'guest', 'customer', 'kitchen', 'staff', 'manager', 'admin', 'superadmin'],
    allowedActorTypes: ['guest', 'customer', 'kitchen', 'staff', 'manager', 'admin', 'superadmin'],
    requiredPermissions: ['orders.read'],
    requiresConfirmation: false,
    supportsIdempotency: false,
    riskLevel: 'READ_ONLY',
    rateLimit: 'standard',
    rateLimitClass: 'standard',
    auditRequired: false,
    enabled: true,
    timeoutMs: 5000,
    retryPolicy: { maxRetries: 2, retryable: true },
    destructive: false,
    sensitiveData: false,
    ownershipScope: 'order'
  },

  get_reservation_availability: {
    id: 'tool_reservation_get_availability_legacy',
    name: 'get_reservation_availability',
    toolName: 'get_reservation_availability',
    category: 'RESERVATION',
    purpose: 'Check live capacity and table/hujra availability for a date, time, and guest count.',
    description: 'Check available tables and traditional private Hujra suites.',
    version: '1.0.0',
    status: 'IMPLEMENTED',
    parameters: {
      type: Type.OBJECT,
      properties: {
        date: { type: Type.STRING, description: 'Target date (YYYY-MM-DD or Tonight/Tomorrow)' },
        time: { type: Type.STRING, description: 'Arrival time (e.g. 8:30 PM)' },
        guests: { type: Type.NUMBER, description: 'Party size (1-50)' }
      },
      required: ['date', 'time', 'guests']
    },
    inputSchema: '{ date: string, time: string, guests: number }',
    outputSchema: 'ReservationAvailabilityObject',
    requiresAuth: false,
    allowedRoles: ['anonymous', 'guest', 'customer', 'kitchen', 'staff', 'manager', 'admin', 'superadmin'],
    allowedActorTypes: ['guest', 'customer', 'kitchen', 'staff', 'manager', 'admin', 'superadmin'],
    requiredPermissions: ['reservations.read'],
    requiresConfirmation: false,
    supportsIdempotency: false,
    riskLevel: 'READ_ONLY',
    rateLimit: 'standard',
    rateLimitClass: 'standard',
    auditRequired: false,
    enabled: true,
    timeoutMs: 5000,
    retryPolicy: { maxRetries: 2, retryable: true },
    destructive: false,
    sensitiveData: false,
    ownershipScope: 'public'
  },

  get_loyalty_status: {
    id: 'tool_loyalty_get_status_legacy',
    name: 'get_loyalty_status',
    toolName: 'get_loyalty_status',
    category: 'LOYALTY',
    purpose: 'Check loyalty points balance, tier perks, and reward vouchers.',
    description: 'Get authoritative loyalty points balance and redemption vouchers.',
    version: '1.0.0',
    status: 'IMPLEMENTED',
    parameters: { type: Type.OBJECT, properties: {} },
    inputSchema: '{}',
    outputSchema: 'LoyaltyStatusObject',
    requiresAuth: true,
    allowedRoles: ['customer', 'staff', 'manager', 'admin', 'superadmin'],
    allowedActorTypes: ['customer', 'staff', 'manager', 'admin', 'superadmin'],
    requiredPermissions: ['loyalty.read'],
    requiresConfirmation: false,
    supportsIdempotency: false,
    riskLevel: 'READ_ONLY',
    rateLimit: 'standard',
    rateLimitClass: 'standard',
    auditRequired: false,
    enabled: true,
    timeoutMs: 5000,
    retryPolicy: { maxRetries: 2, retryable: true },
    destructive: false,
    sensitiveData: true,
    ownershipScope: 'user'
  },

  submit_support_ticket: {
    id: 'tool_support_submit_ticket_legacy',
    name: 'submit_support_ticket',
    toolName: 'submit_support_ticket',
    category: 'SUPPORT',
    purpose: 'Log customer feedback, special requests, or waiter calls for immediate management attention.',
    description: 'Log customer feedback or inquiries for restaurant floor management.',
    version: '1.0.0',
    status: 'IMPLEMENTED',
    parameters: {
      type: Type.OBJECT,
      properties: {
        customerName: { type: Type.STRING, description: 'Customer name' },
        message: { type: Type.STRING, description: 'Feedback or inquiry message' },
        phone: { type: Type.STRING, description: 'Contact number if follow-up required' }
      },
      required: ['customerName', 'message']
    },
    inputSchema: '{ customerName: string, message: string, phone?: string }',
    outputSchema: 'SupportTicketResult',
    requiresAuth: false,
    allowedRoles: ['anonymous', 'guest', 'customer', 'kitchen', 'staff', 'manager', 'admin', 'superadmin'],
    allowedActorTypes: ['guest', 'customer', 'kitchen', 'staff', 'manager', 'admin', 'superadmin'],
    requiredPermissions: ['support.write'],
    requiresConfirmation: false,
    supportsIdempotency: true,
    riskLevel: 'LOW_RISK_WRITE',
    rateLimit: 'standard',
    rateLimitClass: 'standard',
    auditRequired: true,
    enabled: true,
    timeoutMs: 5000,
    retryPolicy: { maxRetries: 1, retryable: true },
    destructive: false,
    sensitiveData: false,
    ownershipScope: 'public'
  },

  get_kitchen_status: {
    id: 'tool_ops_get_kitchen_status_legacy',
    name: 'get_kitchen_status',
    toolName: 'get_kitchen_status',
    category: 'RESTAURANT_OPERATIONS',
    purpose: 'View active kitchen ticket queue, items currently preparing, and queue latency.',
    description: '[OPERATIONAL] View active KDS queue and kitchen prep load.',
    version: '1.0.0',
    status: 'IMPLEMENTED',
    parameters: { type: Type.OBJECT, properties: {} },
    inputSchema: '{}',
    outputSchema: 'KitchenQueueObject',
    requiresAuth: true,
    allowedRoles: ['kitchen', 'staff', 'manager', 'admin', 'superadmin'],
    allowedActorTypes: ['kitchen', 'staff', 'manager', 'admin', 'superadmin'],
    requiredPermissions: ['kitchen.read'],
    requiresConfirmation: false,
    supportsIdempotency: false,
    riskLevel: 'READ_ONLY',
    rateLimit: 'standard',
    rateLimitClass: 'standard',
    auditRequired: false,
    enabled: true,
    timeoutMs: 5000,
    retryPolicy: { maxRetries: 2, retryable: true },
    destructive: false,
    sensitiveData: false,
    ownershipScope: 'system'
  },

  get_operational_summary: {
    id: 'tool_admin_get_operational_summary_legacy',
    name: 'get_operational_summary',
    toolName: 'get_operational_summary',
    category: 'ADMIN',
    purpose: 'Comprehensive operational overview of today orders, revenue estimates, table occupancy.',
    description: '[OPERATIONAL] View today operational metrics and active tickets.',
    version: '1.0.0',
    status: 'IMPLEMENTED',
    parameters: { type: Type.OBJECT, properties: {} },
    inputSchema: '{}',
    outputSchema: 'OperationalSummaryObject',
    requiresAuth: true,
    allowedRoles: ['staff', 'manager', 'admin', 'superadmin'],
    allowedActorTypes: ['staff', 'manager', 'admin', 'superadmin'],
    requiredPermissions: ['reports.read'],
    requiresConfirmation: false,
    supportsIdempotency: false,
    riskLevel: 'READ_ONLY',
    rateLimit: 'privileged',
    rateLimitClass: 'privileged',
    auditRequired: false,
    enabled: true,
    timeoutMs: 5000,
    retryPolicy: { maxRetries: 2, retryable: true },
    destructive: false,
    sensitiveData: true,
    ownershipScope: 'system'
  },

  admin_update_price: {
    id: 'tool_admin_update_price_legacy',
    name: 'admin_update_price',
    toolName: 'admin_update_price',
    category: 'ADMIN',
    purpose: '[ADMIN ONLY] Update the price of a menu item in the authoritative database.',
    description: '[ADMIN ONLY] Update the price of a menu item in the authoritative database.',
    version: '1.0.0',
    status: 'IMPLEMENTED',
    parameters: {
      type: Type.OBJECT,
      properties: {
        itemIdOrName: { type: Type.STRING, description: "Item ID or name (e.g. 'Zafrani Chai')" },
        newPrice: { type: Type.NUMBER, description: 'New price in PKR' },
        reason: { type: Type.STRING, description: 'Reason for price adjustment' }
      },
      required: ['itemIdOrName', 'newPrice']
    },
    inputSchema: '{ itemIdOrName: string, newPrice: number, reason?: string }',
    outputSchema: 'PriceUpdateResult',
    requiresAuth: true,
    allowedRoles: ['admin', 'superadmin'],
    allowedActorTypes: ['admin', 'superadmin'],
    requiredPermissions: ['menu.write'],
    requiresConfirmation: false,
    supportsIdempotency: true,
    riskLevel: 'LOW_RISK_WRITE',
    rateLimit: 'privileged',
    rateLimitClass: 'privileged',
    auditRequired: true,
    enabled: true,
    timeoutMs: 8000,
    retryPolicy: { maxRetries: 1, retryable: true },
    destructive: false,
    sensitiveData: false,
    ownershipScope: 'system'
  },

  admin_toggle_availability: {
    id: 'tool_admin_toggle_availability_legacy',
    name: 'admin_toggle_availability',
    toolName: 'admin_toggle_availability',
    category: 'ADMIN',
    purpose: '[ADMIN/KITCHEN] Toggle menu item availability (mark in-stock or 86 out of stock).',
    description: '[ADMIN/KITCHEN] Toggle menu item availability (in-stock or 86).',
    version: '1.0.0',
    status: 'IMPLEMENTED',
    parameters: {
      type: Type.OBJECT,
      properties: {
        itemIdOrName: { type: Type.STRING, description: 'Item ID or name' },
        isAvailable: { type: Type.BOOLEAN, description: 'true if available, false if sold out' }
      },
      required: ['itemIdOrName', 'isAvailable']
    },
    inputSchema: '{ itemIdOrName: string, isAvailable: boolean }',
    outputSchema: 'AvailabilityToggleResult',
    requiresAuth: true,
    allowedRoles: ['kitchen', 'staff', 'manager', 'admin', 'superadmin'],
    allowedActorTypes: ['kitchen', 'staff', 'manager', 'admin', 'superadmin'],
    requiredPermissions: ['kitchen.write'],
    requiresConfirmation: false,
    supportsIdempotency: true,
    riskLevel: 'LOW_RISK_WRITE',
    rateLimit: 'privileged',
    rateLimitClass: 'privileged',
    auditRequired: true,
    enabled: true,
    timeoutMs: 8000,
    retryPolicy: { maxRetries: 1, retryable: true },
    destructive: false,
    sensitiveData: false,
    ownershipScope: 'system'
  },

  admin_update_order_status: {
    id: 'tool_admin_update_order_status_legacy',
    name: 'admin_update_order_status',
    toolName: 'admin_update_order_status',
    category: 'ADMIN',
    purpose: '[ADMIN/KITCHEN] Advance order lifecycle (confirmed -> preparing -> ready -> out_for_delivery -> completed).',
    description: '[ADMIN/KITCHEN] Update order status in live kitchen workflow.',
    version: '1.0.0',
    status: 'IMPLEMENTED',
    parameters: {
      type: Type.OBJECT,
      properties: {
        orderId: { type: Type.STRING, description: 'Order ID' },
        status: { type: Type.STRING, description: "'confirmed' | 'preparing' | 'ready' | 'out_for_delivery' | 'completed' | 'cancelled'" },
        notes: { type: Type.STRING, description: 'Staff note on order update' }
      },
      required: ['orderId', 'status']
    },
    inputSchema: '{ orderId: string, status: string, notes?: string }',
    outputSchema: 'OrderStatusUpdateResult',
    requiresAuth: true,
    allowedRoles: ['kitchen', 'staff', 'manager', 'admin', 'superadmin'],
    allowedActorTypes: ['kitchen', 'staff', 'manager', 'admin', 'superadmin'],
    requiredPermissions: ['kitchen.write'],
    requiresConfirmation: false,
    supportsIdempotency: true,
    riskLevel: 'LOW_RISK_WRITE',
    rateLimit: 'privileged',
    rateLimitClass: 'privileged',
    auditRequired: true,
    enabled: true,
    timeoutMs: 8000,
    retryPolicy: { maxRetries: 1, retryable: true },
    destructive: false,
    sensitiveData: false,
    ownershipScope: 'order'
  },

  admin_broadcast_announcement: {
    id: 'tool_admin_broadcast_announcement_legacy',
    name: 'admin_broadcast_announcement',
    toolName: 'admin_broadcast_announcement',
    category: 'ADMIN_CONFIG',
    purpose: '[ADMIN ONLY] Update public announcement and promotional marquee banner across all user screens.',
    description: '[ADMIN ONLY] Update public announcement and promotional banner across all user apps.',
    version: '1.0.0',
    status: 'IMPLEMENTED',
    parameters: {
      type: Type.OBJECT,
      properties: {
        message: { type: Type.STRING, description: 'Announcement text to display on banners' }
      },
      required: ['message']
    },
    inputSchema: '{ message: string }',
    outputSchema: 'AnnouncementResult',
    requiresAuth: true,
    allowedRoles: ['admin', 'superadmin'],
    allowedActorTypes: ['admin', 'superadmin'],
    requiredPermissions: ['configuration.write'],
    requiresConfirmation: false,
    supportsIdempotency: true,
    riskLevel: 'LOW_RISK_WRITE',
    rateLimit: 'privileged',
    rateLimitClass: 'privileged',
    auditRequired: true,
    enabled: true,
    timeoutMs: 8000,
    retryPolicy: { maxRetries: 1, retryable: true },
    destructive: false,
    sensitiveData: false,
    ownershipScope: 'system'
  },

  admin_get_operational_report: {
    id: 'tool_admin_get_operational_report_legacy',
    name: 'admin_get_operational_report',
    toolName: 'admin_get_operational_report',
    category: 'ADMIN',
    purpose: '[ADMIN ONLY] Generate comprehensive operational report on sales, active reservations, popular items, and system health.',
    description: '[ADMIN ONLY] Generate comprehensive operational report on sales, active reservations, popular items.',
    version: '1.0.0',
    status: 'IMPLEMENTED',
    parameters: {
      type: Type.OBJECT,
      properties: {
        timeframe: { type: Type.STRING, description: "Timeframe: 'today', 'shift', 'week'" }
      }
    },
    inputSchema: '{ timeframe?: string }',
    outputSchema: 'OperationalReportObject',
    requiresAuth: true,
    allowedRoles: ['admin', 'superadmin'],
    allowedActorTypes: ['admin', 'superadmin'],
    requiredPermissions: ['reports.read'],
    requiresConfirmation: false,
    supportsIdempotency: false,
    riskLevel: 'READ_ONLY',
    rateLimit: 'privileged',
    rateLimitClass: 'privileged',
    auditRequired: false,
    enabled: true,
    timeoutMs: 8000,
    retryPolicy: { maxRetries: 2, retryable: true },
    destructive: false,
    sensitiveData: true,
    ownershipScope: 'system'
  },

  admin_manage_reservations: {
    id: 'tool_admin_manage_reservations_legacy',
    name: 'admin_manage_reservations',
    toolName: 'admin_manage_reservations',
    category: 'ADMIN',
    purpose: '[STAFF/ADMIN] View and manage all guest reservations for today or specified date.',
    description: '[STAFF/ADMIN] List and manage reservations across dining hall and Hujra suites.',
    version: '1.0.0',
    status: 'IMPLEMENTED',
    parameters: {
      type: Type.OBJECT,
      properties: {
        filterDate: { type: Type.STRING, description: 'Date to filter, or empty for all' }
      }
    },
    inputSchema: '{ filterDate?: string }',
    outputSchema: 'ReservationListObject',
    requiresAuth: true,
    allowedRoles: ['staff', 'manager', 'admin', 'superadmin'],
    allowedActorTypes: ['staff', 'manager', 'admin', 'superadmin'],
    requiredPermissions: ['reservations.read'],
    requiresConfirmation: false,
    supportsIdempotency: false,
    riskLevel: 'READ_ONLY',
    rateLimit: 'privileged',
    rateLimitClass: 'privileged',
    auditRequired: false,
    enabled: true,
    timeoutMs: 8000,
    retryPolicy: { maxRetries: 2, retryable: true },
    destructive: false,
    sensitiveData: true,
    ownershipScope: 'system'
  }
};

export const TOOL_ALIASES: Record<string, string> = {
  // Customer info aliases
  getrestaurantinfo: 'restaurant_information',
  getbusinesshours: 'restaurant_hours',
  getrestauranthours: 'restaurant_hours',
  getcontactinformation: 'restaurant_contact',
  getlocation: 'restaurant_information',
  getrestaurantpolicies: 'restaurant_information',
  getmenu: 'search_menu',
  getmenucategory: 'get_menu_categories',
  searchmenu: 'search_menu',
  getmenuitem: 'get_menu_item',
  getitemavailability: 'get_menu_item',
  getitemoptions: 'get_menu_item',
  getcurrentuserprofile: 'customer_profile',
  getcustomerprofile: 'customer_profile',
  updateallowedprofilefields: 'update_customer_preferences',
  getcustomerpreferences: 'customer_memory',
  getcustomermemory: 'customer_memory',
  saveallowedcustomerpreference: 'update_customer_preferences',
  updatecustomerpreferences: 'update_customer_preferences',

  // Order aliases
  createorder: 'create_order',
  getorder: 'get_order',
  getorderstatus: 'order_status',
  updateorder: 'update_order',
  cancelorder: 'cancel_order',
  orderstatus: 'order_status',
  orderhistory: 'order_history',
  getcustomerorders: 'order_history',
  calculateordertotal: 'calculate_order_quote',
  calculateorderquote: 'calculate_order_quote',
  validateorder: 'calculate_order_quote',
  checkitemavailability: 'get_menu_item',

  // Reservation aliases
  checktableavailability: 'reservation_availability',
  getreservationavailability: 'reservation_availability',
  createreservation: 'create_reservation',
  getreservation: 'get_reservation',
  updatereservation: 'update_reservation',
  modifyreservation: 'update_reservation',
  cancelreservation: 'cancel_reservation',
  getcustomerreservations: 'admin_manage_reservations',
  getreservationssummary: 'admin_manage_reservations',

  // Support aliases
  submitsupportticket: 'create_support_request',
  createsupportrequest: 'create_support_request',
  getsupportrequest: 'get_support_request',
  customersupporthistory: 'customer_support_history',

  // Notification aliases
  createnotification: 'create_notification',
  sendnotification: 'send_notification',
  sendcustomernotification: 'send_notification',
  notificationstatus: 'notification_status',
  getnotificationpreferences: 'customer_profile',

  // Loyalty aliases
  loyaltystatus: 'loyalty_status',
  getloyaltystatus: 'loyalty_status',
  loyaltyhistory: 'loyalty_history',
  getloyaltypoints: 'loyalty_status',
  eligiblerewards: 'eligible_rewards',
  calculateeligiblereward: 'eligible_rewards',
  redeemreward: 'eligible_rewards',

  // Kitchen / operations aliases
  kitchenorderstatus: 'kitchen_order_status',
  getkitchenorders: 'kitchen_order_status',
  getkitchenstatus: 'kitchen_order_status',
  kitchenqueue: 'kitchen_queue',
  getkitchenqueue: 'kitchen_queue',
  driverdispatch: 'driver_dispatch',
  getdeliveryqueue: 'driver_dispatch',
  assigndelivery: 'order_management',
  deliverystatus: 'delivery_status',
  updatedeliverystatus: 'order_management',
  getdriverstatus: 'driver_dispatch',

  // Admin aliases
  restaurantconfiguration: 'restaurant_configuration',
  readrestaurantconfiguration: 'restaurant_configuration',
  updaterestaurantconfiguration: 'restaurant_configuration',
  menumanagement: 'menu_management',
  managemenu: 'menu_management',
  manageavailability: 'menu_management',
  ordermanagement: 'order_management',
  updatekitchenorderstatus: 'order_management',
  markpreparing: 'order_management',
  markready: 'order_management',
  reservationmanagement: 'reservation_management',
  customermanagement: 'customer_management',
  getcustomersummary: 'customer_management',
  notificationmanagement: 'notification_management',
  managenotificationconfiguration: 'notification_management',
  operationalreports: 'operational_reports',
  getoperationalsummary: 'operational_reports',
  getorderssummary: 'operational_reports',
  getmenusummary: 'search_menu',
  getrestauranthealth: 'operational_reports',
  getauditlogs: 'operational_reports',
  generateoperationalreport: 'operational_reports',

  // AI aliases
  restaurantknowledgesearch: 'restaurant_knowledge_search',
  customercontext: 'customer_context',
  conversationcontext: 'conversation_context',

  // Super admin aliases
  superadminsystemdiagnostics: 'superadmin_system_diagnostics',
  getsystemhealth: 'superadmin_system_diagnostics'
};

export function resolveToolName(name: string): string {
  const direct = TOOL_REGISTRY[name];
  if (direct) return name;
  const normalized = name.toLowerCase().replace(/[-_]/g, '');
  return TOOL_ALIASES[normalized] || name;
}
